export const projects = [
  {
    title: 'Thomas & Company, CPA',
    type: 'Website',
    job: 'Freelance',
    role: 'Frontend',
    description: 'The official client-facing website of Thomas & Company, a niche CPA firm in San Jose, CA.',
    imageURL: '/assets/office-background-1.jpg',
    frontend: 'url',
    backend: '',
    live: true,
    private: true,
    deploy: 'https://thomasandcompanycpa.com/',
    technologies: ['NextJS', 'CSS3', 'Material UI', 'Vercel'],
  },

  {
    title: 'Ashleigh King Counseling',
    type: 'Website',
    job: 'Freelance',
    role: 'Frontend',
    description: 'Private practice website for marriage and family therapy in Carlsbad, CA.',
    imageURL: '/assets/ash-background.jpg',
    frontend: 'url',
    backend: '',
    live: true,
    private: true,
    deploy: 'https://www.ashkingcounseling.com/',
    technologies: ['NextJS', 'CSS3', 'Material UI', 'Vercel'],
  },

  {
    title: 'Austin Thomas Dev',
    type: 'Website',
    job: 'Personal',
    role: 'Full Stack',
    description: 'My personal portfolio site (which you are currently on!)',
    imageURL: '/assets/austin-thomas-web-dev.png',
    frontend: 'https://github.com/austin-c-thomas/austin-thomas-dev',
    backend: '',
    live: true,
    private: false,
    deploy: '/',
    technologies: ['NextJS', 'CSS3', 'Material UI', 'Vercel'],
  },

  {
    title: 'The Sketch Shoppe',
    type: 'Website',
    job: 'Bootcamp Project',
    role: 'Full Stack',
    description: 'A functional e-commerce site for selling reasonably sketchy things.',
    imageURL: '/assets/sketch-shoppe.png',
    frontend: 'https://github.com/Reasonably-Sketchy/GraceShopperFrontend',
    backend: 'https://github.com/Reasonably-Sketchy/GraceShopperBackend',
    live: true,
    private: false,
    deploy: 'https://sketch-shoppe.netlify.app/',
    technologies: ['ReactJS', 'Node/ExpressJS', 'PostgreSQL', 'CSS3', 'Material UI', 'Netlify', 'Heroku', 'Git'],
  },

  // {
  //   title: `Fitness Trackr`,
  //   type: 'App',
  //   job: 'Bootcamp Project',
  //   role: 'Full Stack',
  //   description: 'An app for creating and sharing fitness routines.',
  //   imageURL: '/assets/fitness-trackr.png',
  //   frontend: 'https://github.com/austin-c-thomas/UNIV_FitnessTrackr_React_Austin_Richard',
  //   backend: 'https://github.com/austin-c-thomas/UNIV_FitnessTrackr_Starter',
  //   live: true,
  //   private: true,
  //   deploy: 'https://fitness-trackr-austin-richard.netlify.app/',
  //   technologies: ['ReactJS', 'Node/ExpressJS', 'PostgreSQL', 'CSS3', 'Netlify', 'Heroku', 'Git'],
  // },

  // {
  //   title: `Stranger's Things`,
  //   type: 'App',
  //   job: 'Bootcamp Project',
  //   role: 'Frontend',
  //   description: 'A digital marketplace app built around a 3rd party API.',
  //   imageURL: '/assets/strangers-things.png',
  //   frontend: 'https://github.com/austin-c-thomas/strangers-things',
  //   backend: '',
  //   live: true,
  //   private: false,
  //   deploy: 'https://austins-strangers-things.netlify.app/',
  //   technologies: ['ReactJS', 'CSS3', 'Material UI', 'Netlify', 'Git'],
  // },

]